name: spark-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyspark=4.1.1
  - pandas=2.2.0
  - numpy=1.26.4
  - jupyter=1.0.0
  - matplotlib=3.8.2
  - seaborn=0.13.1
  - scikit-learn=1.4.0
  - pip=23.3
  - pip:
    - findspark==2.0.1
    - pyarrow==15.0.0
    - plotly==5.18.0
    - ydata-profiling==4.6.4
    - statsmodels==0.14.1
    - prophet==1.1.5
    - pmdarima==2.0.4
    - delta-spark==3.0.0
    - pyyaml==6.0.1
    - python-dotenv==1.0.0
    - tqdm==4.66.1